const TYPE_ADVANTAGE = {
    Fire: {
      Fire: 1,
      Water: 0.5,
      Plant: 2,
      Earth: 1,
      Wind: 0.5,
      Shock: 1,
      Beast: 2,
      Mystic: 1,
      None: 1,
    },
    Water: {
      Fire: 2,
      Water: 1,
      Plant: 0.5,
      Earth: 2,
      Wind: 1,
      Shock: 0.5,
      Beast: 1,
      Mystic: 1,
      None: 1,
    },
    Plant: {
      Fire: 0.5,
      Water: 2,
      Plant: 1,
      Earth: 2,
      Wind: 1,
      Shock: 1,
      Beast: 0.5,
      Mystic: 1,
      None: 1,
    },
    Earth: {
      Fire: 1,
      Water: 0.5,
      Plant: 0.5,
      Earth: 1,
      Wind: 1,
      Shock: 2,
      Beast: 2,
      Mystic: 1,
      None: 1,
    },
    Wind: {
      Fire: 2,
      Water: 1,
      Plant: 1,
      Earth: 1,
      Wind: 1,
      Shock: 1,
      Beast: 1,
      Mystic: 0.5,
      None: 1,
    },
    Shock: {
      Fire: 1,
      Water: 2,
      Plant: 1,
      Earth: 0.5,
      Wind: 1,
      Shock: 1,
      Beast: 1,
      Mystic: 1,
      None: 1,
    },
    Beast: {
      Fire: 0.5,
      Water: 1,
      Plant: 2,
      Earth: 0.5,
      Wind: 1,
      Shock: 1,
      Beast: 1,
      Mystic: 2,
      None: 1,
    },
    Mystic: {
      Fire: 1,
      Water: 1,
      Plant: 1,
      Earth: 1,
      Wind: 2,
      Shock: 1,
      Beast: 0.5,
      Mystic: 1,
      None: 1,
    },
    None: {
      Fire: 1,
      Water: 1,
      Plant: 1,
      Earth: 1,
      Wind: 1,
      Shock: 1,
      Beast: 1,
      Mystic: 1,
      None: 1,
    },
  };